export const ADD_ITEM = "ADD_ITEM";
export const DELETE_ITEM = "DELETE_ITEM";
export const FILTER_CONTACTS = "FILTER_CONTACTS";

export const CONTACT_REQUEST_START = "CONTACT_REQUEST_START";
export const CONTACT_REQUEST_SUCCESS = "CONTACT_REQUEST_SUCCESS";
export const CONTACT_DELETE_START = "CONTACT_DELETE_START";
export const CONTACT_DELETE_SUCCESS = "CONTACT_DELETE_SUCCESS";

export const CONTACT_REQUEST_ERROR = "CONTACT_REQUEST_ERROR";
export const ERROR_RESET = "ERROR_RESET";
export const DELETE_ERROR = "DELETE_ERROR";
